spring:
  application:
    name: iara-api-mongo

  data:
    mongodb:
      uri: ${MONGO_URI}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /api-docs

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  storage-bucket: ${SUPABASE_BUCKET}

model:
  url: ${MODEL_URL}

